[package]
name = "orderbook-x"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "orderbook_benchmark"
harness = false

[dependencies]
indexmap = { version = "2", features = ["rayon", "serde"] }
rayon = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.price]
workspace = true

[dependencies.proptest]
workspace = true

[dependencies.test-strategy]
workspace = true

[dependencies.criterion]
workspace = true
