[package]
name = "orderbook-x"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "orderbook_benchmark"
harness = false

[dependencies]
indexmap = { version = "2", features = ["rayon", "serde"] }
tracing = "0.1"

[dev-dependencies]
rand = "0.8"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.price]
workspace = true

[dependencies.serde]
workspace = true

[dev-dependencies.proptest]
workspace = true

[dev-dependencies.criterion] # used in benches
workspace = true
