// version of protocol buffer used
syntax = "proto3";

// package name for the buffer will be used later
package api;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply);
}

message HelloRequest {
 string name = 1;
}

message HelloReply {
  string message = 1;
}

service CommandApi {
  // Update Orderbook Actions
  /*
  Limit Order Types is GTC (Good Till Cancelled) currently.
  Fill or Kill (FOK) - not supported yet
  Immediate or Cancel (IOC) - not supported yet
  */
  rpc InsertMarketBuyOrder (InsertMarketBuyOrderRequest) returns (InsertOrderReply);
  rpc InsertMarketSellOrder (InsertMarketSellOrderRequest) returns (InsertOrderReply);
  rpc InsertLimitBuyOrder (InsertLimitBuyOrderRequest) returns (InsertOrderReply);
  rpc RemoveBuyOrder (RemoveOrderRequest) returns (RemoveOrderReply);
  rpc InsertLimitSellOrder (InsertLimitSellOrderRequest) returns (InsertOrderReply);
  rpc RemoveSellOrder (RemoveOrderRequest) returns (RemoveOrderReply);
}

// Get highest bid or lowest ask
message ClosestOrderRequest {

}

message OrderReply {
  float order_price = 1;
  uint64 qty = 2;
}

// GTC Limit Buy Order
message InsertLimitBuyOrderRequest {
  float order_price = 2;
  uint64 identifier = 3;
  uint64 qty = 4;
}

// GTC Limit Sell Order
message InsertLimitSellOrderRequest {
  float order_price = 2;
  uint64 identifier = 3;
  uint64 qty = 4;
}

message InsertMarketBuyOrderRequest {
  uint64 identifier = 1;
  uint64 qty = 2;
}

message InsertMarketSellOrderRequest {
  uint64 identifier = 1;
  uint64 qty = 2;
}

message InsertOrderReply {
  bool success = 1;
}

// Remove Order
message RemoveOrderRequest {
  float order_price = 1;
  uint64 identifier = 2;
}

message RemoveOrderReply {
  bool success = 1;
}

service QueryApi {
  // Get Orderbook Actions
  rpc GetHighestBid (ClosestOrderRequest) returns (OrderReply);
  rpc GetLowestAsk (ClosestOrderRequest) returns (OrderReply);
  rpc GetBids (BuySideRequest) returns (OrderbookReply);
  rpc GetAsks (SellSideRequest) returns (OrderbookReply);
}

// Get buy side of the Orderbook
message BuySideRequest {
  uint64 depth = 1;
}

// Get sell side of the Orderbook
message SellSideRequest {
  uint64 depth = 1;
}

// Orderbook reply of buy or sell side
message OrderbookReply {
  bytes serialized_orderbook = 1;
}
